dist: trusty
language: go
go_import_path: github.com/coreos/zetcd
sudo: false

go:
  - 1.8
  - tip

env:
  global:
   - GO15VENDOREXPERIMENT=1
  matrix:
   - TARGET=amd64


matrix:
  fast_finish: true
  allow_failures:
    - go: tip

script:
 - go get -t -v ./...; go test -v -race ./integration
